### ISSUE TITLE
QT Creator says binaries need to be installed properly

### ISSUE THREAD

**Issue by davidm71** [alberthdev/alberthdev-misc#3]
Hi,

I guess I gave up trying to compile my own so I down loaded your precompiled version. Interesting that VS2013 did not complain about their inclusion but QT Creator had an error message that they need to be properly installed. Is there a proper hard coded install directory? Also you forsee issues with VS2013 as yours are vetted on VS2015? Only have 2013 pro license. Would 2015 community work?

Thanks

**Comment by alberthdev** [comment]
Hi there!

> I guess I gave up trying to compile my own so I down loaded your precompiled version.

What happened? I'm kind of curious to know if anything changed since I wrote the guide. Definitely willing to work with you to get the guide fixed if you encountered anything odd!

> Interesting that VS2013 did not complain about their inclusion but QT Creator had an error message that they need to be properly installed. Is there a proper hard coded install directory?

It depends on the build - I don't remember off the top of my head how Qt's builds handle it, but these are the folders from my builds:

 * Qt v5.6.0 Win32: `C:\Qt\Qt5.6.0\`
 * Qt v5.6.0 Win64: `C:\Qt\Qt5.6.0x64\`
 * Qt v5.6.0 Win32 Static: `C:\Qt\Qt5.6.0-static\`
 * Qt v5.6.0 Win64 Static: `C:\Qt\Qt5.6.0x64-static\`

Try to specify that directory, and then potentially one of the subdirectories. I will say that the builds I've made (and any builds that could be made) don't seem to match up with the official folder structure, for whatever reason... so it's not just you!

If you're still having issues, I'd recommend looking at [this](http://doc.qt.io/qtcreator/creator-project-qmake.html), which might be a workaround for automatically detecting "installations" of Qt. Make sure you are using the latest version of Qt Creator!

> Also you forsee issues with VS2013 as yours are vetted on VS2015? Only have 2013 pro license. Would 2015 community work?

I don't think VS2015 is backwards compatible with VS2013, but you're definitely free to try and link your program with it! This might be more of a MSVC question - which from initial research, doesn't seem to let you go backwards... but feel free to prove me wrong! (If you're using static builds, MSVC libraries are embedded in the build - that may or may not help you out!)

VS 2015 Community definitely works - it's free, and it contains a good chunk of functionality needed to get this going! It also has much of the "pro" functionality (ATL/MFC headers, etc.) - the only thing to note is that if you're doing commercial development, there's some [restrictions](https://www.visualstudio.com/vs/compare/) in terms of size, but I think you'll be fine.

**Comment by davidm71** [comment]
Hi!

> What happened? I'm kind of curious to know if anything changed since I wrote the guide. Definitely willing to work with you to get the guide fixed if you encountered anything odd!

I had trouble following all the steps in your guide. So downloaded the precompiled version which makes VS 2013 error upon build that version numbers don't match, and 2015 community just gives some error right off the bat. Not sure why.

> It depends on the build - I don't remember off the top of my head how Qt's builds handle it, but these are the folders from my builds:
> 
> Qt v5.6.0 Win32: C:\Qt\Qt5.6.0\
> Qt v5.6.0 Win64: C:\Qt\Qt5.6.0x64\
> Qt v5.6.0 Win32 Static: C:\Qt\Qt5.6.0-static\
> Qt v5.6.0 Win64 Static: C:\Qt\Qt5.6.0x64-static\

Will try using those exact folder names and report back. Fwiw I just tried using another guide to compile my own at [http://amin-ahmadi.com/2015/07/03/how-to-build-qt-5-5-static-libraries-using-any-microsoft-visual-c-compiler/)](url). Seemed like there were less steps. 

But your precompiled modules would be a godsend if I can get them to work.

**Comment by alberthdev** [comment]
> I had trouble following all the steps in your guide.

Definitely curious to know what steps you have trouble with, and exactly why they were troublesome!

> So downloaded the precompiled version which makes VS 2013 error upon build that version numbers don't match, and 2015 community just gives some error right off the bat. Not sure why.

VS2013 erroring makes sense... but VS2015 Community not so much, since I built the libraries with VS2015 Community. What are the errors you are getting? (Copy+paste the errors if you can!)

> Fwiw I just tried using another guide to compile my own at http://amin-ahmadi.com/2015/07/03/how-to-build-qt-5-5-static-libraries-using-any-microsoft-visual-c-compiler/). Seemed like there were less steps.

These steps are outdated, since the latest Qt (5.6+) no longer needs any special modifications to successfully compile statically with MSVC. (No more editing required!)

My guide has a few more steps because my builds intend to include OpenSSL, a library that is not normally included in builds. (For static linking, we have to build this in, or be forced to include OpenSSL as a separate DLL.)

If you do NOT need (or want) OpenSSL, you can jump to step 3. Remove any SSL/OpenSSL related configuration flags from the build script, and then proceed.

**Comment by davidm71** [comment]
Hi,
Thanks for the interest in figuring this out. I am literally going nuts trying to figure this out. So basically in either VS2013 or VS2015 when selecting your compiled qt kits after opening up a demo helloworld type application and trying to build it I get this error:

1>------ Build started: Project: myqtWidget, Configuration: Debug x64 ------
1>  Moc'ing myqtwidget.h...
1>  Uic'ing myqtwidget.ui...
1>  Rcc'ing myqttext.qrc...
1>  moc_myqtwidget.cpp
1>  main.cpp
1>  myqtwidget.cpp
1>  myqtwidget_plugin_import.cpp
1>c1xx : fatal error C1083: Cannot open source file: 'C:\Users\david\Documents\myqtWidget\myqtwidget_plugin_import.cpp': No such file or directory
1>  Generating Code...
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========


The other problem is trying to create a fresh QT Pro Project using the Visual Studio 'New File' templates I don't have the ability to press the finish button except for once with the QT_5.60_Rel64 package but with that one I get an Exception HResult error #x80041FE2. 

Anyhow I have found that these precompiled packages work better in QT Creator fwiw and getting it to work in VS is just for bragging rights. Just wish it would work.

Thanks

**Comment by davidm71** [comment]
Update: I finally got it to work after installing Visual Studio Tools in the installer for Community 2015. There was one message that said it needed where I hadn't noticed before so had nothing to lose and it seems to work with out error on the 5.60-x64 release kit. What confuses me though is why do you need two kits one for release and one for debug? Seems like the release works in debug mode. 
Thanks

**Comment by alberthdev** [comment]
Sorry for the delay in response! The debug build is a must if you want to be able to trace through Qt calls instead of seeing meaningless stack traces! My binaries include both release and debug builds in one, so you can easily switch configurations like that.

**Comment by Kolychii84** [comment]
3N2cwaHfgnF8eDQ68B8ezytgsnXAEg3HdS
